version: '3.3'
services:
  db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080